package com.xiaojun.boaoshuangpingji.beans;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xiaojun.boaoshuangpingji.beans.BaoCunBean;
import com.xiaojun.boaoshuangpingji.beans.BaoCunId;

import com.xiaojun.boaoshuangpingji.beans.BaoCunBeanDao;
import com.xiaojun.boaoshuangpingji.beans.BaoCunIdDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baoCunBeanDaoConfig;
    private final DaoConfig baoCunIdDaoConfig;

    private final BaoCunBeanDao baoCunBeanDao;
    private final BaoCunIdDao baoCunIdDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baoCunBeanDaoConfig = daoConfigMap.get(BaoCunBeanDao.class).clone();
        baoCunBeanDaoConfig.initIdentityScope(type);

        baoCunIdDaoConfig = daoConfigMap.get(BaoCunIdDao.class).clone();
        baoCunIdDaoConfig.initIdentityScope(type);

        baoCunBeanDao = new BaoCunBeanDao(baoCunBeanDaoConfig, this);
        baoCunIdDao = new BaoCunIdDao(baoCunIdDaoConfig, this);

        registerDao(BaoCunBean.class, baoCunBeanDao);
        registerDao(BaoCunId.class, baoCunIdDao);
    }
    
    public void clear() {
        baoCunBeanDaoConfig.clearIdentityScope();
        baoCunIdDaoConfig.clearIdentityScope();
    }

    public BaoCunBeanDao getBaoCunBeanDao() {
        return baoCunBeanDao;
    }

    public BaoCunIdDao getBaoCunIdDao() {
        return baoCunIdDao;
    }

}
